# Generated by Django 4.2.2 on 2023-09-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentialsapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField(blank=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('account_type', models.CharField(blank=True, choices=[('S', 'Savings'), ('C', 'Current')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='credentialsapp.branch')),
                ('district', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='credentialsapp.district')),
            ],
        ),
    ]
